### ISSUE TITLE
这个taskprogress 只能在SU2017下使用

### ISSUE THREAD

**Issue by LItterBoy-GB** [SketchUp/sketchup-taskbarlist#6]
这个taskprogress 只能在SU2017下使用

**Comment by thomthom** [comment]
This example was  written before SU2017 - and the Ruby 2.2 libs are missing.

However,  the Ruby C Extension example projects is updated and you can copy the source code from this into that project: https://github.com/SketchUp/ruby-c-extension-examples

**Comment by LItterBoy-GB** [comment]
这个我知道的  我是更新了三方库 然后在17下测试的 15  16测试都没有通过
而且 我自己写dll 通过Fiddle调用也是没有成功的  
我说的不成功是指  15 16依旧是单线程 这个任务进度没有进度条的效果

**Comment by LItterBoy-GB** [comment]
我的意思是  这个在17以下  只支持短时间进度    长时间SU依旧是会卡死的
[SU2016 test](https://youtu.be/SeeEq-PRXJY)
[SU2017 test](https://youtu.be/XFnCqy2fL3c)

**Comment by thomthom** [comment]
Can you post the test model and code snippet please?

**Comment by LItterBoy-GB** [comment]
@thomthom  sorry,It was delayed, and then I forgot.
